### ISSUE TITLE
Compatibility with the new Quark Enchantment Table GUI

### ISSUE THREAD

**Issue by WenXin20** [Block-Vader/Enchantment-tweaks#4]
Recently Quark Oddities (r1.5-140) added a new Enchantment Table GUI and function. Is it possible for compatibility to be added for this? 

Currently the new Quark GUI will appear, but then after a couple of seconds, the GUI from this mod will replace it.

**Comment by Block-Vader** [comment]
Turns ouf there isn't a simple way to do it. I would have to reimplement quark enchanting system by myself.

**Comment by frenchiveruti** [comment]
So the bookshelves that you add won't work with quark's system?

**Comment by WenXin20** [comment]
I didn't test that part, what was happening was that the GUI kept changing from Quark's GUI to a normal GUI, but it's been a while since I've used this mod. I think in the end it ended up working fine.
